name: Sync to Gitee
on: [ push ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Black list
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/hinpc
        dst: gitee/gallenhu
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 用于 git ssh 的私钥
        dst_token: ${{ secrets.GITEE_TOKEN }}
        clone_style: "ssh"
        # 仅同步这个repo,按需修改
        static_list: ${{ github.event.repository.name }}
        force_update: true
        debug: true
        timeout: '1h'
